#!/bin/sh /etc/rc.common
# Copyright 2018. Spotlight Cybersecurity LLC
# Released under an MIT license. See LICENSE file.
#
# init.d script for OpenWRT using procd to start daemonlogger.
# Note that you can have multiple capture sections in /etc/config/daemonlogger

START=99
STOP=01
USE_PROCD=1

handle_capture() {
	local section="$1"
	config_get intf "$section" 'interface'
	config_get odir "$section" 'outputdir'
	config_get rotatetime "$section" 'time'
	config_get bpf "$section" 'bpf'
	config_get name "$section" 'name'

	if [[ ! -d "$odir" ]]; then
		echo "The output directory doesn't exist!"
		return 1
	fi

	procd_open_instance "$section"
	procd_set_param command /usr/bin/daemonlogger -i "$intf" -n "${name}" -l "${odir}" -t "${rotatetime}" "${bpf}"
	procd_set_param respawn
	procd_close_instance
}

start_service() {
	config_load daemonlogger
	config_foreach handle_capture
}

